//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YS.Sequence.Impl.EFCore.SqlServer.Migrations._20200105122945.StoredProcedures {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Procs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Procs() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YS.Sequence.Impl.EFCore.SqlServer.Migrations._20200105122945.StoredProcedures.Pro" +
                            "cs", typeof(Procs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 create procedure CreateSequence 
        ///(
        /// @seqenceName varchar(128),
        /// @startValue bigint=1 ,
        /// @step int=1,
        /// @EndValue bigint =NULL
        ///)
        ///AS
        ///begin
        ///IF @seqenceName IS NULL BEGIN
        ///    RAISERROR(&apos;The @seqenceName should not be null.&apos;,11,1)
        ///    RETURN 0
        ///   END 
        ///   IF @startValue IS NULL BEGIN
        ///    RAISERROR(&apos;The @startValue should not be null.&apos;,11,1)
        ///    RETURN 0
        ///   END
        ///   IF @step IS NULL BEGIN 
        ///    RAISERROR(&apos;The @step should not be null.&apos;,11,1)
        ///    RETURN 0
        ///   END 
        ///   IF dbo.ExistsSequence(@seqenceName)=1 BEGIN
        ///    RAISE [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CreateSequence {
            get {
                return ResourceManager.GetString("CreateSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CREATE procedure DeleteSequence
        ///(
        /// @seqenceName varchar(128)
        ///)
        ///as
        ///begin
        /// delete Sequences  where [Name]=@seqenceName
        /// return @@rowcount
        ///end
        ///go 的本地化字符串。
        /// </summary>
        internal static string DeleteSequence {
            get {
                return ResourceManager.GetString("DeleteSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 create procedure GetOrCreateSequenceValue 
        ///(
        ///  @seqenceName varchar(128),
        ///  @currentValue bigint output
        ///)
        ///AS
        ///BEGIN
        /// DECLARE @tmp bigint,@flag int 
        /// UPDATE Sequences
        /// SET
        ///  @flag=1,
        ///  @currentValue= ISNULL (CurrentValue,StartValue),
        ///  @tmp=@currentValue+STEP,
        ///  CurrentValue=CASE WHEN EndValue IS NULL THEN @tmp  
        ///      WHEN  @tmp&gt;EndValue THEN @tmp%EndValue+StartValue-1 
        ///      ELSE @tmp END
        /// WHERE [Name]=@seqenceName 
        /// 
        /// IF @flag IS NULL--说明没有找到记录
        /// BEGIN
        ///   INSERT INTO Sequences([Name]) VALUES(@seqenceName) - [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string GetOrCreateSequenceValue {
            get {
                return ResourceManager.GetString("GetOrCreateSequenceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 create procedure GetSequenceInfo 
        ///(
        /// @seqenceName varchar(128) 
        ///)
        ///AS
        ///BEGIN
        /// SELECT * FROM Sequences WHERE [Name]=@seqenceName
        /// RETURN @@ROWCOUNT
        ///END
        ///go 的本地化字符串。
        /// </summary>
        internal static string GetSequenceInfo {
            get {
                return ResourceManager.GetString("GetSequenceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 create procedure GetSequenceValue 
        ///(
        /// @seqenceName varchar(128),
        /// @currentValue bigint output
        ///)
        ///AS
        ///BEGIN
        /// DECLARE @tmp bigint,@flag int 
        /// UPDATE Sequences
        /// SET
        ///  @flag=1,
        ///  @currentValue= ISNULL (CurrentValue,StartValue),
        ///  @tmp=@currentValue+STEP,
        ///  CurrentValue=CASE WHEN EndValue IS NULL THEN @tmp  
        ///      WHEN  @tmp&gt;EndValue THEN @tmp%EndValue+StartValue-1 
        ///      ELSE @tmp END
        /// WHERE [Name]=@seqenceName 
        /// RETURN @flag
        ///END
        ///go 的本地化字符串。
        /// </summary>
        internal static string GetSequenceValue {
            get {
                return ResourceManager.GetString("GetSequenceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 create procedure ResetSequence 
        ///(
        /// @seqenceName varchar(128)
        ///)
        ///AS
        ///BEGIN
        /// UPDATE Sequences
        /// SET CurrentValue = NULL 
        /// WHERE [Name]=@seqenceName
        /// RETURN @@ROWCOUNT
        ///END
        ///go 的本地化字符串。
        /// </summary>
        internal static string ResetSequence {
            get {
                return ResourceManager.GetString("ResetSequence", resourceCulture);
            }
        }
    }
}
