version: '3.3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
  init_context:
    depends_on: 
      - db
    build: 
      context: ../
      dockerfile: YS.Sequence.App/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__SequenceContext: Server=db;Port=3306;Database=SequenceContext; User=root;Password=my-secret-pw;
    entrypoint: /scripts/wait-for-it.sh db:3306 -s -t 0 -- dotnet YS.Sequence.App.dll install
    volumes:
      - ../scripts/:/scripts/
  api:
    depends_on: 
      - db
    build: 
      context: ../
      dockerfile: YS.Sequence.App/Dockerfile
    ports:
    - "${API_PORT:-8080}:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__SequenceContext: Server=db;Port=3306;Database=SequenceContext; User=root;Password=my-secret-pw;
