name: deploy

on:
  push:
    branches:
      - master

jobs:
  package:

    runs-on: ubuntu-latest

    steps:
    - name: 01 Checkout Code
      uses: actions/checkout@v1
    - name: 02 Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: 03 Create Package
      run: dotnet pack -o .publish --configuration Release
    - name: 04 Push Package
      run: bash ./.github/scripts/pushpack.sh .publish ${{secrets.NUGET_APIKEY}}
